# Generated by Django 4.2.16 on 2025-01-24 11:32

from django.db import migrations, models
import knowledge.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', knowledge.models.VectorField(blank=True, dimensions=1536, null=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
