# Generated by Django 4.2.16 on 2025-01-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_chatsession_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_id',
            field=models.CharField(default='1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
