# Generated by Django 4.2.16 on 2025-01-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_document_chunk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docstring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['chunk_id'], name='document_chunk_i_57f756_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_path'], name='document_file_pa_3a12a0_idx'),
        ),
    ]
